name: Export PDF

on:
  workflow_dispatch:

jobs:
  export_pdf:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Export webpage as PDF
      run: |
        cat > safari_export_pdf.scpt <<-EOF
        tell application "Safari"
          activate
          set theURL to "https://www.scottatron.com"
          set theFile to ("${PWD}/output.pdf") as POSIX file
          make new document with properties {URL:theURL}
          delay 5
          set the bounds of the front window to {0, 0, 960, 1080}
          delay 2
          export the front document to theFile as PDF
          close the front document
        end tell
        EOF
        osascript safari_export_pdf.scpt


    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output.pdf
