name: Export PDF

on:
  push:
  workflow_dispatch:

jobs:
  export_pdf:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set version
        run: echo "version=$(git log -1 --date=format:%Y-%m-%d --pretty=format:%cd-%h)" >> $GITHUB_ENV

      - name: Wait until Netlify has deployed
        if: ${{ github.ref_name == 'main' }}
        run: |
          until make deployed
          do
            echo "Waiting for Netlify to deploy..."
            sleep 1
          done

      - name: Allow bash to control Safari
        run: |
          epochdate=$(($(date +'%s * 1000 + %-N / 1000000')))
          tcc_service_appleevents="replace into access (service,client,client_type,auth_value,auth_reason,auth_version,indirect_object_identifier_type,indirect_object_identifier,flags,last_modified) values (\"kTCCServiceAppleEvents\",\"/bin/bash\",1,2,4,1,0,\"com.apple.Safari\",0,$epochdate);"
          sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "$tcc_service_appleevents"

      - name: Export webpage as PDF
        run: |
          cat > safari_export_pdf.scpt <<-EOF
          with timeout of 30 seconds
            tell application "Safari"
              activate
              set theURL to "https://www.scottatron.com"
              make new document with properties {URL:theURL}
              delay 5
            end tell
          end timeout

          tell application "System Events"
            tell process "Safari"
              set frontmost to true
              set size of window 1 to {960, 1080}
              delay 0.5
              click menu item "Export as PDF…" of menu "File" of menu bar 1
              with timeout of 5 seconds
                repeat until exists sheet 1 of window 1
                  delay 0.02
                end repeat
              end timeout
              keystroke "h" using {command down, shift down} -- go to the home directory
              set theFile to "Scott-Arthur-CV-${{ env.version }}.pdf"
              set value of text field 1 of sheet 1 of window 1 to theFile
              click button "Save" of sheet 1 of window 1
              delay 0.5
            end tell
          end tell
          EOF
          osascript safari_export_pdf.scpt
          mv ~/*.pdf .
        # https://github.com/create-dmg/create-dmg/issues/72#issuecomment-959514966

      - run: screencapture screen.png
        if: ${{ failure() }}

      - uses: actions/upload-artifact@v3
        with:
          name: screen.png
          path: screen.png
        if: ${{ failure() }}

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: Scott-Arthur-CV-${{ env.version }}.pdf

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.pdf"
          tag: ${{ env.version }}
          makeLatest: true
          token: ${{ secrets.RELEASE_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
