name: Export PDF

on:
  workflow_dispatch:

jobs:
  export_pdf:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set version
        run: echo "version=$(git log -1 --date=format:%Y-%m-%d --pretty=format:%cd-%h)" >> $GITHUB_ENV

      - name: Start screencapture
        run: screencapture -T0 -V30 screen.mov

      - name: Export webpage as PDF
        id: applescript
        run: |
          cat > safari_export_pdf.scpt <<-EOF
          tell application "Safari"
            activate
            set theURL to "https://www.scottatron.com"
            make new document with properties {URL:theURL}
            delay 0.5
          end tell

          tell application "System Events"
            tell process "Safari"
              set frontmost to true
              set size of window 1 to {960, 1080}
              delay 0.5
              click menu item "Export as PDF…" of menu "File" of menu bar 1
              repeat until exists sheet 1 of window 1
                delay 0.02
              end repeat
              -- keystroke "h" using {command down, shift down} -- go to the home directory
              set theFile to "${PWD}/Scott-Arthur-CV-${{ env.version }}.pdf" as POSIX file
              set value of text field 1 of sheet 1 of window 1 to theFile
              click button "Save" of sheet 1 of window 1
              delay 0.5
            end tell
          end tell

          tell application "Safari"
            close the front document
          end tell
          EOF
          osascript safari_export_pdf.scpt

      - run: screencapture screen.png
        if: ${{ failure() }}

      - uses: actions/upload-artifact@v2
        with:
          name: screen
          path: screen.png
        if: ${{ steps.applescript.outcome != 'success' }}

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: Scott-Arthur-PDF-${{ env.version }}.pdf
